### PR TITLE
feat: gpg client

### PR DESCRIPTION
**Pull request by kjanat**
This pull request introduces a comprehensive set of improvements focused on developer experience, documentation quality, and project configuration for the GPG Signing Service. The main highlights include the addition of production-ready API documentation files and guides, enhancements to code formatting and linting configurations, and updates to CI/CD workflow and pre-commit hooks. These changes collectively ensure that the project is easier to use, integrate, and maintain, with clear standards and robust documentation for both developers and integrators.

**Documentation and Developer Guides:**

- Added a full suite of API documentation and guides, including `DEVELOPER_GUIDE.md`, `DOCS_SUMMARY.txt`, and an updated architecture diagram in `README.md`, providing navigation, key concepts, common tasks, endpoint overviews, and integration checklists for the GPG Signing Service. [[1]](diffhunk://#diff-d5555724c2ebca1b1f9be92a74c90e84c2dcbc76631148801024e24372b7edc6R1-R336) [[2]](diffhunk://#diff-df6f5acee906ccbf765f1b099f418e3e35d8155bd4f7f5665eae2bdc0a52dbf5R1-R246) [[3]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R17-R32)
- Updated `CLAUDE.md` to improve the project structure section formatting for clarity.

**Code Formatting and Linting:**

- Introduced `.editorconfig` and `.dprint.jsonc` to enforce consistent code style and formatting across multiple file types, including TypeScript, JSON, YAML, Markdown, and more. [[1]](diffhunk://#diff-0947e2727d6bad8cd0ac4122f5314bb5b04e337393075bc4b5ef143b17fcbd5bR1-R28) [[2]](diffhunk://#diff-4b0a264a7578f955622f1573a2e9eefec4f81e5e03481b841691b4811855ec8bR1-R80)
- Added `.commitlint.ts` to enforce conventional commit message standards.
- Enhanced `.lefthook.yml` to improve pre-commit and pre-push hooks, add staged formatting, and introduce commit message linting.

**CI/CD and Workflow Updates:**

- Adjusted `.github/workflows/sign-commits.yml` and `.gitlab-ci.yml` to ensure correct branch targeting and commit signing rules, aligning workflows across platforms. [[1]](diffhunk://#diff-4b34ac88ad81e629184e9cf4ba6b46732f75e8cb47cbedd03fde787e09dca499L5-R5) [[2]](diffhunk://#diff-037ea159eb0a7cb0ac23b851e66bee30fb838ee8d0d99fa331a1ba65283d37f7L2-R2) [[3]](diffhunk://#diff-037ea159eb0a7cb0ac23b851e66bee30fb838ee8d0d99fa331a1ba65283d37f7L63-R63)

**Project Cleanliness and Ignore Rules:**

- Updated `.prettierignore` to fine-tune which files and directories are excluded from formatting, ensuring only relevant files are processed.

These updates provide a strong foundation for both contributors and users, improving onboarding, integration, and ongoing project maintenance.

## Summary by CodeRabbit

* **New Features**
  * OpenAPI-driven API + interactive docs UI, remote commit signing, key management, audit logging, new Go CLI and Python helpers, request-id middleware and OpenAPI-backed routes.
* **Documentation**
  * Complete API reference, developer guide, examples, quick-starts, migration guides and CI/CD/operational playbooks.
* **Infrastructure**
  * CI/security workflows, formatting/linting/tooling standardization, task automation, reusable CI actions and ignore/secret scanning configs.
* **Tests**
  * Large expansion of unit/integration tests covering signing, rate limits, durable storage, middleware, client behavior and error paths.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Comment by kjanat** [comment]
@codex review

**Comment by kjanat** [comment]
@coderabbitai review

**Comment by kjanat** [comment]
@coderabbitai review

File: client/openapi.json [hunk 1]
```diff
@@ -0,0 +1,729 @@
...
+                  "$ref": "#/components/schemas/ErrorResponse"
+                }
+              }
+            }
+          }
+        }
+      }
+    }
+  }
+}
```
[the remark this answers is not in the document]
Comment (kjanat) [reply client/openapi.json:790]: THIS FILE IS AUTO-GENERATED BLYAT!!!

File: client/openapi.json [hunk 2]
```diff
@@ -0,0 +1,729 @@
...
+          }
+        },
+        "required": [
+          "armoredPrivateKey",
+          "keyId"
+        ]
+      }
+    },
+    "parameters": {}
+  },
```
[the remark this answers is not in the document]
Comment (kjanat) [reply client/openapi.json:322]: @coderabbitai SAME HERE... OPENAPI SCHEMA IS AUTO-GENERATED!!! COMMENT ON THE *.ts CODE

File: client/pkg/client/options_test.go [hunk 3]
```diff
@@ -0,0 +1,264 @@
...
+	}
+}
+
+// BenchmarkDefaultOptions benchmarks creating default options
+func BenchmarkDefaultOptions(b *testing.B) {
+
+	for b.Loop() {
+		_ = defaultOptions()
+	}
+}
```
[the remark this answers is not in the document]
Comment (kjanat) [reply client/pkg/client/options_test.go:262]: @coderabbitai

The claim that `b.Loop()` is not valid Go benchmark syntax and will cause a compilation error is not true. In fact, `b.Loop()` is a valid and recommended method introduced in Go 1.24 as a more efficient and cleaner way to write benchmarks. It replaces the older standard loop `for i := 0; i < b.N; i++` by simplifying the benchmark loop control and improving setup and timing accuracy.

Details about `b.Loop()` in Go benchmarking:

- `b.Loop()` runs the benchmark loop correctly by controlling iterations behind the scenes.
- It prevents setup code from running repeatedly and automates timer management.
- It avoids compiler optimizations that might invalidate benchmarks.
- After `b.Loop()` exits, `b.N` holds the total iterations run, just like the traditional approach.
- This method requires writing the loop as `for b.Loop() { ... }` inside the benchmark function and works fine in Go 1.24 and newer.

Alternate forms in Go 1.22+ for benchmarks using `b.N` can use `for range b.N { ... }`, which is a concise syntax for looping over an integer count.

In short:

- The original snippet replacing `for b.Loop()` with `for i := 0; i < b.N; i++` is not necessary unless targeting older Go versions before 1.24.
- Using `for b.Loop()` is currently the preferred and modern way to write Go benchmarks for better accuracy and less error-prone code.
- If using Go 1.22 or later but before 1.24, `for range b.N` is an alternative valid syntax.

Hence, the statement that `b.Loop()` is not valid syntax causing compilation failure is incorrect for Go versions 1.24+ where `b.Loop()` is fully supported and encouraged.[^1][^2][^3][^4][^5]

[^1]: https://go.dev/blog/testing-b-loop
[^2]: https://www.bytesizego.com/blog/go-124-new-benchmark-function
[^3]: https://betterstack.com/community/guides/scaling-go/golang-benchmarking/
[^4]: https://www.ardanlabs.com/blog/2024/03/for-loops-and-more-in-go.html
[^5]: https://golang.bg/pkg/testing/
[^6]: https://www.reddit.com/r/golang/comments/1lp1fum/bloop_misunderstanding/
[^7]: https://www.linkedin.com/posts/diwakar-singh-_go-nugget-are-you-still-using-the-%F0%9D%90%9F%F0%9D%90%A8%F0%9D%90%AB-activity-7371061523877777408-obpE
[^8]: https://dave.cheney.net/2013/06/30/how-to-write-benchmarks-in-go
[^9]: https://jarosz.dev/code/benchmarking-what-you-cannot-miss-in-go-1.24/
[^10]: https://stackoverflow.com/questions/16920669/improving-testing-benchmark-for-go
[^11]: https://www.willem.dev/articles/benchmarks-performance-testing/
[^12]: https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/iteration
[^13]: http://mcclain.sh/posts/go-benchmarking/
[^14]: https://github.com/golang/go/issues/61515
[^15]: https://forum.golangbridge.org/t/for-loops-performance/34225
[^16]: https://forum.golangbridge.org/t/for-range-with-ints/36975
[^17]: https://gobyexample.com/testing-and-benchmarking
[^18]: https://www.practical-go-lessons.com/chap-34-benchmarks
[^19]: https://stackoverflow.com/questions/21950244/is-there-a-way-to-iterate-over-a-range-of-integers)
[^20]: https://dev.to/mfbmina/go-124-benchmark-tests-439b

**Comment by kjanat** [comment]
@coderabbitai pause

**Comment by kjanat** [comment]
@coderabbitai resume
